sonarr:
    image: madgoat/sonarr
    ports:
      - "8989:8989"
    net: "host"
    container_name: sonarr
    volumes:
            - /mnt/tv:/tv
            - /mnt/config/sonarr:/config
            - /mnt/completed:/completed
            - /mnt/downloads:/downloads
    restart: always
