couchpotato:
    image: madgoat/couchpotato
    ports:
      - "5050:5050"
    net: "host"
    container_name: couchpotato
    volumes:
            - /mnt/movies:/media
            - /mnt/config/couchpotato:/datadir
    restart: always
