couchpotato:
    image: madgoat/couchpotato
    ports:
      - "5050:5050"
    net: "host"
    container_name: couchpotato
    volumes:
            - /mnt/media-server/movies:/media
            - /mnt/media-server/couchpotato:/datadir
    restart: always
