nzbget:
    image: madgoat/nzbget
    ports:
      - "6789:6789"
    net: "host"
    container_name: nzbget
    volumes:
            - /mnt/tv:/tv
            - /mnt/movies:/movies
            - /mnt/downloads:/downloads
            - /mnt/config/nzbget:/config
    restart: always
